tasks:
 - name: Run NPM install
   init: npm install
 - name: Install mob.sh
   init: curl -sL install.mob.sh | sudo sh
 - name: Run Tests
   command: npm run test:watch
   
vscode:
  extensions:
    - dbaeumer.vscode-eslint